tags:
  - name: Auth
    description: Everything about authentication
  - name: Invention
    description: Everything about uploading your inventions
  - name: User
    description: Everything about the user

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: User registration
      operationId: RegisterUser
      requestBody:
        description: Creates a new user
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        '201':
          description: Created
        '400':
          description: Bad request
        '409':
          description: Conflict
        '500':
          description: Internal server error

  /auth/verify:
    post:
      tags:
        - Auth
      summary: Verify user
      operationId: VerifyUser
      requestBody:
        description: Verify user account
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyUser'
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /auth/resendotp:
    post:
      tags:
        - Auth
      summary: Resend OTP
      operationId: ResendOtp
      requestBody:
        description: Resend OTP to user's email
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendOtp'
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Internal server error

  /auth/login:
    post:
      tags:
        - Auth
      summary: User login
      operationId: LoginUser
      requestBody:
        description: User logs in to account
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /auth/refresh:
    get:
      tags:
        - Auth
      summary: Refresh user access token
      operationId: RefreshToken
      responses:
        '200':
          description: Success
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

  /auth/logout:
    get:
      security:
        - bearerAuth: []
      tags:
        - Auth
      summary: User logs out from the application
      operationId: UserLogout
      responses:
        '204':
          description: Success
        '403':
          description: Forbidden
        '500':
          description: Internal server error

  /inventions:
    post:
      security:
        - bearerAuth: []
      tags:
        - Invention
      summary: Upload your invention
      operationId: UploadInvention
      requestBody:
        description: User uploads their inventions
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadInvention'
      responses:
        '201':
          description: Created
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

    get:
      security:
        - bearerAuth: []
      tags:
        - Invention
      summary: Get all inventions
      operationId: GetAllInventions
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /inventions/{inventionId}:
    parameters:
      - in: path
        name: inventionId
        schema:
          type: string
        required: true
        description: Invention ID
    get:
      security:
        - bearerAuth: []
      tags:
        - Invention
      summary: Get a single invention
      operationId: GetSingleInvention
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
        '500':
          description: Internal server error

  /users/me:
    get:
      security:
        - bearerAuth: []
      tags:
        - User
      summary: Get logged in user information
      operationId: GetUser
      responses:
        '200':
          description: Success
        '500':
          description: Internal server error

  /users/{userId}:
    parameters:
      - in: path
        name: userId
        schema:
          type: string
        required: true
        description: User ID
    delete:
      security:
        - bearerAuth: []
      tags:
        - User
      summary: Delete user
      operationId: DeleteUser
      responses:
        '204':
          description: Success
        '400':
          description: Bad request
        '403':
          description: Forbidden
        '500':
          description: Internal server error

    get:
      security:
        - bearerAuth: []
      tags:
        - User
      summary: Get a user by their ID
      operationId: GetUserById
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterUser:
      type: object
      properties:
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          example: johndoe@example.com
        password:
          type: string
          example: 12345678
        passwordConfirm:
          type: string
          example: 12345678
    VerifyUser:
      type: object
      properties:
        userId:
          type: string
          example: 643f2486adbcb274dv9b4752
        otp:
          type: string
          example: 2hJu
    ResendOtp:
      type: object
      properties:
        userId:
          type: string
          example: 643f2486adbcb274dv9b4752
        email:
          type: string
          example: johndoe@example.com
    LoginUser:
      type: object
      properties:
        email:
          type: string
          example: johndoe@example.com
        password:
          type: string
          example: 12345678
    UploadInvention:
      required:
        - productName
        - productCategory
        - description
        - keyFeatures
        - keyBenefit
        - productPicture
      type: object
      properties:
        productName:
          type: string
          example: My Invented cleaner
        productCategory:
          type: string
          example: Home appliance
        description:
          type: string
          example: My Invented cleaner is a tool that helps in cleaning your home.
        keyFeatures:
          type: string
          example:
            The most important feature of this product is that it cleans automatically when it spots
            dirt.
        keyBenefit:
          type: string
          example: It helps reduce stress of cleaning.
        size:
          type: string
          example: 30cm x 30cm
        weight:
          type: string
          example: 3000 grammes
        materialsUsed:
          type: string
          example: The materials used includes plastic, aluminium
        productPicture:
          type: string
          format: binary
        productVideo:
          type: string
          format: binary
        productDemo:
          type: string
          format: binary
